{% set name = "murky" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/murky-{{ version }}.tar.gz
  sha256: 0923257e06f984eb3070cefcd24a6fdef047ab7b4ac7b6d2877c9fdafc77e6e2

build:
  # skip: true  # [py<3.8 or py>=311]
  entry_points:
    - create_release_notes = murky.create_release_notes:main
    - murky_tool = murky.murky_tool:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pygithub
    - pyyaml

test:
  imports:
    - murky
  commands:
    - pip check
    - create_release_notes --help
    - murky_tool --help
  requires:
    - pip

about:
  home: https://github.com/prjemian/murky/
  summary: The murky package provides tools for working with conda packages.
  license: CC0-1.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - prjemian
