{% set name = "murky" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/murky-{{ version }}.tar.gz
  sha256: 6a46f3b2e74d9efe498d2ec7cfebcb3509c63301aa966eaf7ace12b362dd21bb

build:
  # skip: true  # [py<3.8 or py>=312]
  entry_points:
    - create_release_notes = murky.create_release_notes:main
    - murky_tool = murky.murky_tool:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python
    - versioneer
  run:
    - python
    - pygithub
    - pyyaml
    - versioneer

test:
  imports:
    - murky
  commands:
    - pip check
    - create_release_notes --help
    - murky_tool --help
  requires:
    - pip

about:
  home: https://github.com/prjemian/murky/
  summary: The murky package provides tools for working with conda packages.
  license: CC0-1.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - prjemian
